### ISSUE TITLE
slider not working with me!

### ISSUE THREAD

**Issue by NourhanMagdy92** [CodyHouse/hero-slider#3]
Hello, please help me. I am a beginner and I want to use the hero slider in my website. I downloaded all files, copy the code of the body, files of Css and js and images but the slider not working.
**note:** I use jquery.min.js version 3.3.1 and bootstrap version 4.0.0. 
please please help me and thanks in advance.
**[here](https://app.box.com/s/n5b01i5k0lawewh56vrree238kd9s7r1)** my code @claudia-romano

**Comment by sebastiano-guerriero** [comment]
Hi there! I'm afraid we can't provide support for integration (other than the info included in the tutorial/article on CodyHouse). Cheers

**Comment by NourhanMagdy92** [comment]
I followed the tutorial by the way but what about demo.css, where is it ?!!!
